package org.caleydo.core.command.view.rcp;

public enum EExternalFlagSetterType
{
	PATHWAY_GENE_MAPPING,
	PATHWAY_TEXTURES,
	PATHWAY_NEIGHBORHOOD,
	// PATHWAY_IDENTICAL_NODE_HIGHLIGHTING,
	PATHWAY_ANNOTATION,
	PARCOORDS_OCCLUSION_PREVENTION,
}
