package org.caleydo.core.command.view.rcp;

public enum EExternalActionType
{
	CLEAR_ALL,
	CLEAR_SELECTIONS,
	REMOTE_RENDERING_TOGGLE_LAYOUT_MODE,
	STORAGEBASED_PROPAGATE_SELECTIONS,
	PARCOORDS_ANGULAR_BRUSHING,
}
