package org.caleydo.core.command.view.rcp;

public enum EExternalActionType
{
	CLOSE_OR_RESET_CONTAINED_VIEWS,
	REMOTE_RENDERING_TOGGLE_LAYOUT_MODE,
	REMOTE_RENDERING_TOGGLE_CONNECTION_LINES_MODE,
	PARCOORDS_ANGULAR_BRUSHING,
	PARCOORDS_SAVE_SELECTIONS,
	PARCOORDS_RESET_AXIS_SPACING,
	STORAGEBASED_PROPAGATE_SELECTIONS,
	CLEAR_SELECTIONS,
	STORAGEBASED_RESET_VIEW;
}
