package org.caleydo.core.command.view.rcp;

public enum EExternalFlagSetterType {
	PATHWAY_GENE_MAPPING,
	PATHWAY_TEXTURES,
	PATHWAY_NEIGHBORHOOD,
	// PATHWAY_IDENTICAL_NODE_HIGHLIGHTING,
	PATHWAY_ANNOTATION,
	PARCOORDS_OCCLUSION_PREVENTION,
	STORAGEBASED_CHANGE_ORIENTATION,
	STORAGEBASED_HEATMAP_IN_FOCUS,
	STORAGEBASED_USE_RANDOM_SAMPLING,
	STORAGEBASED_RENDER_CONTEXT,

	GLYPH_VIEWMODE_SCATTERLOT,
	GLYPH_VIEWMODE_RECTANGLE,
	GLYPH_VIEWMODE_CIRCLE,
	GLYPH_VIEWMODE_RANDOM,
	GLYPH_VIEWMODE_PLUS,
	GLYPH_SELECTION,
}
