package org.caleydo.core.command.view.rcp;

@Deprecated
public enum EExternalObjectSetterType {
	GLYPH_SELECTIONBRUSH,
	GLYPH_CHANGEPERSONALNAME,
	GLYPH_CHANGE_SCATTERPLOT_AXIS_X,
	GLYPH_CHANGE_SCATTERPLOT_AXIS_Y,
	GLYPH_CHANGE_PLUSMODEL_AXIS_X,
	GLYPH_CHANGE_PLUSMODEL_AXIS_Y,
	STORAGEBASED_START_CLUSTERING,
}
