package org.caleydo.view.visbricks;

/**
 * 
 * Picking Types for VisBricks
 * 
 * @author Alexander Lex
 * 
 */
public enum PickingType {

	BRICK,
	BRICK_EXPAND_BUTTON,
	BRICK_COLLAPSE_BUTTON,
	BRICK_CLOSE_BUTTON,
	BRICK_DETAIL_MODE_BUTTON,
	BRICK_TOOLBAR_VIEW_SWITCHING_BUTTONS,
	BRICK_VIEW_SWITCHING_MODE_BUTTON,
	BRICK_LOCK_RESIZING_BUTTON,
	BRICK_CONNECTION_BAND,
	RESIZE_HANDLE_UPPER_LEFT,
	RESIZE_HANDLE_UPPER_RIGHT,
	RESIZE_HANDLE_LOWER_LEFT,
	RESIZE_HANDLE_LOWER_RIGHT,
	MOVE_VERTICALLY_HANDLE,
	MOVE_HORIZONTALLY_HANDLE,
	EXPAND_LEFT_HANDLE,
	EXPAND_RIGHT_HANDLE,

	DIMENSION_GROUP_CLUSTER_BUTTON,
	DIMENSION_GROUP,
	DIMENSION_GROUP_SPACER;
}
