
var Description = {
	getDescription : function(code) {
		var d = this.data[code];

		if(d==null)
			return "no description found";

		return d;
	},

	data : {
		"a00-b99.png" : "Bestimmte infektioese und parasitaere Krankheiten",
		"c00-d48.png" : "Neubildungen",
		"d50-d89.png" : "Krankheiten des Blutes und der blutbildenden Organe sowie bestimmte Stoerungen mit Beteiligung des Immunsystems",
		"e00-e90.png" : "Endokrine, Ernaehrungs- und Stoffwechselkrankheiten",
		"f00-f99.png" : "Psychische und Verhaltensstoerungen",
		"g00-g99.png" : "Krankheiten des Nervensystems",
		"h00-h59.png" : "Krankheiten des Auges und der Augenanhangsgebilde",
		"h60-h95.png" : "Krankheiten des Ohres und des Warzenfortsatzes",
		"i00-i99.png" : "Krankheiten des Kreislaufsystems",
		"j00-j99.png" : "Krankheiten des Atmungssystems",
		"k00-k93.png" : "Krankheiten des Verdauungssystems",
		"l00-l99.png" : "Krankheiten der Haut und der Unterhaut",
		"m00-m99.png" : "Krankheiten des Muskel-Skelett-Systems und des Bindegewebes",
		"n00-n99.png" : "Krankheiten des Urogenitalsystems",
		"o00-o99.png" : "Schwangerschaft, Geburt und Wochenbett",
		"p00-p96.png" : "Bestimmte Zustaende, die ihren Ursprung in der Perinatalperiode haben",
		"q00-q96.png" : "Angeborene Fehlbildungen, Deformitaeten und Chromosomenanomalien",
		"r00-r99.png" : "Symptome und abnorme klinische und Laborbefunde, die anderenorts nicht klassifiziert sind",
		"s00-t98.png" : "Verletzungen, Vergiftungen und bestimmte andere Folgen aeusserer Ursachen",
		"v01-y98.png" : "aeussere Ursachen von Morbiditaet und Mortalitaet",
		"z00-z99.png" : "Faktoren, die den Gesundheitszustand beeinflussen und zur Inanspruchnahme des Gesundheitswesens fuehren",



		"Anaesthesiologie und Intensivmedizin.png"            : "Anaesthesiologie und Intensivmedizin",
		"Augenklinik.png"                                     : "Augenklinik",
		"Blutgruppenseriologie und Transfusionsmedizin.png"   : "Blutgruppenseriologie und Transfusionsmedizin",
		"Chirurgie.png"                                       : "Chirurgie",
		"Dermatologie und Venerologie.png"                    : "Dermatologie und Venerologie",
		"Frauenheilkunde und Geburtshilfe.png"                : "Frauenheilkunde und Geburtshilfe",
		"Hals-Nasen-Ohren Universitaetsklinik.png"            : "Hals-Nasen-Ohren Universitaetsklinik",
		"Innere Medizin.png"                                  : "Innere Medizin",
		"Kinder- und Jugendheilkunde.png"                     : "Kinder- und Jugendheilkunde",
		"Kinderchirurgie.png"                                 : "Kinderchirurgie",
		"Medizinische Psychologie und Psychotherapie.png"     : "Medizinische Psychologie und Psychotherapie",
		"Neurochirurgie.png"                                  : "Neurochirurgie",
		"Neurologie.png"                                      : "Neurologie",
		"Orthopaedie.png"                                     : "Orthopaedie",
		"Psychiatrie.png"                                     : "Psychiatrie",
		"Radiologie.png"                                      : "Radiologie",
		"Strahlentherapie und Radioonkologie.png"             : "Strahlentherapie und Radioonkologie",
		"Unfallchirurgie.png"                                 : "Unfallchirurgie",
		"Urologie.png"                                        : "Urologie",
		"Zahn-, Mund- und Kieferheilkunde.png"                : "Zahn-, Mund- und Kieferheilkunde",




		"bauchspeicheldruese_level1.png"     : "Bauchspeicheldruese - Level 1",
		"bauchspeicheldruese_level2.png"     : "Bauchspeicheldruese - Level 2",
		"bauchspeicheldruese_level3.png"     : "Bauchspeicheldruese - Level 3",
		"bauchspeicheldruese_level4.png"     : "Bauchspeicheldruese - Level 4",
		"dickdarm_level1.png"                : "Dickdarm - Level 1",
		"dickdarm_level2.png"                : "Dickdarm - Level 2",
		"dickdarm_level3.png"                : "Dickdarm - Level 3",
		"dickdarm_level4.png"                : "Dickdarm - Level 4",
		"duenndarm_level1.png"               : "Duenndarm - Level 1",
		"duenndarm_level2.png"               : "Duenndarm - Level 2",
		"duenndarm_level3.png"               : "Duenndarm - Level 3",
		"duenndarm_level4.png"               : "Duenndarm - Level 4",
		"entzuendung_level1.png"             : "Entzuendung - Level 1",
		"entzuendung_level2.png"             : "Entzuendung - Level 2",
		"entzuendung_level3.png"             : "Entzuendung - Level 3",
		"entzuendung_level4.png"             : "Entzuendung - Level 4",
		"gehirn_level1.png"                  : "Gehirn - Level 1",
		"gehirn_level2.png"                  : "Gehirn - Level 2",
		"gehirn_level3.png"                  : "Gehirn - Level 3",
		"gehirn_level4.png"                  : "Gehirn - Level 4",
		"harnblase_level1.png"               : "Harnblase - Level 1",
		"harnblase_level2.png"               : "Harnblase - Level 2",
		"harnblase_level3.png"               : "Harnblase - Level 3",
		"harnblase_level4.png"               : "Harnblase - Level 4",
		"herz_level1.png"                    : "Herz - Level 1",
		"herz_level2.png"                    : "Herz - Level 2",
		"herz_level3.png"                    : "Herz - Level 3",
		"herz_level4.png"                    : "Herz - Level 4",
		"knochen_level1.png"                 : "Knochen - Level 1",
		"knochen_level2.png"                 : "Knochen - Level 2",
		"knochen_level3.png"                 : "Knochen - Level 3",
		"knochen_level4.png"                 : "Knochen - Level 4",
		"leber_level1.png"                   : "Leber - Level 1",
		"leber_level2.png"                   : "Leber - Level 2",
		"leber_level3.png"                   : "Leber - Level 3",
		"leber_level4.png"                   : "Leber - Level 4",
		"lokalisation_level1.png"            : "Lokalisation - Level 1",
		"lokalisation_level2.png"            : "Lokalisation - Level 2",
		"lokalisation_level3.png"            : "Lokalisation - Level 3",
		"lokalisation_level4.png"            : "Lokalisation - Level 4",
		"lunge_level1.png"                   : "Lunge - Level 1",
		"lunge_level2.png"                   : "Lunge - Level 2",
		"lunge_level3.png"                   : "Lunge - Level 3",
		"lunge_level4.png"                   : "Lunge - Level 4",
		"magen_level1.png"                   : "Magen - Level 1",
		"magen_level2.png"                   : "Magen - Level 2",
		"magen_level3.png"                   : "Magen - Level 3",
		"magen_level4.png"                   : "Magen - Level 4",
		"mamma_level1.png"                   : "Mamma - Level 1",
		"mamma_level2.png"                   : "Mamma - Level 2",
		"mamma_level3.png"                   : "Mamma - Level 3",
		"mamma_level4.png"                   : "Mamma - Level 4",
		"milz_level1.png"                    : "Milz - Level 1",
		"milz_level2.png"                    : "Milz - Level 2",
		"milz_level3.png"                    : "Milz - Level 3",
		"milz_level4.png"                    : "Milz - Level 4",
		"niere_level1.png"                   : "Niere - Level 1",
		"niere_level2.png"                   : "Niere - Level 2",
		"niere_level3.png"                   : "Niere - Level 3",
		"niere_level4.png"                   : "Niere - Level 4",
		"prostata_level1.png"                : "Prostata - Level 1",
		"prostata_level2.png"                : "Prostata - Level 2",
		"prostata_level3.png"                : "Prostata - Level 3",
		"prostata_level4.png"                : "Prostata - Level 4",
		"schilddruese_level1.png"            : "Schilddruese - Level 1",
		"schilddruese_level2.png"            : "Schilddruese - Level 2",
		"schilddruese_level3.png"            : "Schilddruese - Level 3",
		"schilddruese_level4.png"            : "Schilddruese - Level 4",
		"tumor_level1.png"                   : "Tumor - Level 1",
		"tumor_level2.png"                   : "Tumor - Level 2",
		"tumor_level3.png"                   : "Tumor - Level 3",
		"tumor_level4.png"                   : "Tumor - Level 4",
		"virus_level1.png"                   : "Virus - Level 1",
		"virus_level2.png"                   : "Virus - Level 2",
		"virus_level3.png"                   : "Virus - Level 3",
		"virus_level4.png"                   : "Virus - Level 4"
	}
};

