package org.caleydo.rcp;

public enum EApplicationMode {
	GENE_EXPRESSION_NEW_DATA,
	GENE_EXPRESSION_PATHWAY_VIEWER,
	GENE_EXPRESSION_SAMPLE_DATA_RANDOM,
	GENE_EXPRESSION_SAMPLE_DATA_REAL,
	UNSPECIFIED_NEW_DATA
}
