package org.caleydo.core.data;

import java.io.Serializable;

/**
 * Abstract class providing methods defined in IUniqueManagedObject.
 * 
 * @author Michael Kalkusch
 * @author Marc Streit
 */
public abstract class AUniqueObject
	implements IUniqueObject, Serializable
{
	/**
	 * Unique Id
	 */
	final protected int iUniqueID;

	/**
	 * Constructor.
	 * 
	 * @param iUniqueID the unique ID generated by the system
	 * @param generalManager the general manager
	 */
	protected AUniqueObject(final int iUniqueID)
	{
		this.iUniqueID = iUniqueID;
	}

	@Override
	public final int getID()
	{
		return this.iUniqueID;
	}
}
