package org.caleydo.core.data;

import java.io.Serializable;
import org.caleydo.core.manager.IGeneralManager;

/**
 * Abstract class providing methods defined in IUniqueManagedObject.
 * 
 * @author Michael Kalkusch
 * @author Marc Streit
 */
public abstract class AUniqueObject
	implements IUniqueObject, Serializable
{

	/**
	 * Unique Id
	 */
	protected int iUniqueID;

	/**
	 * Constructor.
	 * 
	 * @param iUniqueID the unique ID generated by the system
	 * @param generalManager the general manager
	 */
	protected AUniqueObject(final int iUniqueID)
	{

		this.iUniqueID = iUniqueID;
	}

	/*
	 * (non-Javadoc)
	 * @see org.caleydo.core.data.IUniqueObject#getId()
	 */
	public final int getId()
	{

		return this.iUniqueID;
	}

	/*
	 * (non-Javadoc)
	 * @see org.caleydo.core.data.IUniqueObject#setId(int)
	 */
	public final void setId(final int iSetDNetEventId)
	{

		this.iUniqueID = iSetDNetEventId;
	}
}
