package org.geneview.core.manager.view;


public enum EPickingType
{
	// overall jukebox
	BUCKET_ICON_SELECTION,	
	VIEW_SELECTION,
		
	// parallel coordinates
	POLYLINE_SELECTION, 
	X_AXIS_SELECTION,	
	Y_AXIS_SELECTION,
	LOWER_GATE_TIP_SELECTION,
	LOWER_GATE_BODY_SELECTION,
	LOWER_GATE_BOTTOM_SELECTION,
	UPPER_GATE_SELECTION,
	PC_ICON_SELECTION,
	MOVE_AXIS_LEFT,
	MOVE_AXIS_RIGHT,
	REMOVE_AXIS,
	DUPLICATE_AXIS,
	
	

	
	// pathway manager
	PATHWAY_ELEMENT_SELECTION,	
	PATHWAY_TEXTURE_SELECTION,
	PATHWAY_POOL_SELECTION,
	MEMO_PAD_SELECTION
	
	
}
