package org.caleydo.core.view;

/**
 * Define the type of the view.
 * 
 * @author Michael Kalkusch
 * @author Marc Streit
 * 
 */
public enum ViewType {
	
	SWT_DATA_EXPLORER,
	SWT_PATHWAY2D,
	SWT_PATHWAY3D,
	SWT_HEATMAP,
	SWT_SLIDER,
	SWT_META_TABLE,
	SWT_HTML_BROWSER,
	SWT_JOGL_VIEW,
	SWT_DATA_TABLE,
	SWT_DATA_EXCHANGER,
	SWT_HISTOGRAM2D,
	SWT_SCATTERPLOT2D,
	SWT_PROGRESSBAR,
	SWT_MIXER,
	SWT_IMAGE_VIEWER,
	SWT_HEATMAP2D,
	SWT_SET_EDITOR,
	SWT_DATA_ENTITY_SEARCHER,
	SWT_GLYPH_MAPPINGCONFIGURATION,
	NONE
}