/*******************************************************************************
 * Caleydo - visualization for molecular biology - http://caleydo.org
 *  
 * Copyright(C) 2005, 2012 Graz University of Technology, Marc Streit, Alexander
 * Lex, Christian Partl, Johannes Kepler University Linz </p>
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *  
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *  
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>
 *******************************************************************************/
package org.caleydo.core.util.base;

/**
 * Abstract class providing methods defined in IUniqueObject.
 * 
 * @author Michael Kalkusch
 * @author Marc Streit
 * @author Alexander Lex
 */
public abstract class AUniqueObject
	implements IUniqueObject {

	/** Unique Id */
	protected int uniqueID;

	/**
	 * default no-arg constructor
	 */
	public AUniqueObject() {
	}

	/**
	 * Constructor.
	 * 
	 * @param uniqueID
	 *            the unique ID generated by the system
	 * @param generalManager
	 *            the general manager
	 */
	protected AUniqueObject(final int uniqueID) {
		this.uniqueID = uniqueID;
	}

	@Override
	public final int getID() {
		return this.uniqueID;
	}

	/**
	 * Returns the internal unique-id as hash code
	 * 
	 * @return internal unique-id as hash code
	 */
	@Override
	public int hashCode() {
		return getID();
	}

	/**
	 * Checks if the given object is equals to this one by comparing the internal unique-id
	 * 
	 * @return <code>true</code> if the 2 objects are equal, <code>false</code> otherwise
	 */
	@Override
	public boolean equals(Object other) {
		if (other instanceof IUniqueObject) {
			return this.getID() == ((IUniqueObject) other).getID();
		}
		else {
			return false;
		}
	}
}
