package org.geneview.core.command.view.rcp;


public enum EExternalFlagSetterType
{
	PATHWAY_ENABLE_GENE_MAPPING,
	PATHWAY_ENABLE_TEXTURES,
	PATHWAY_ENABLE_NEIGHBORHOOD,
	PATHWAY_ENABLE_IDENTICAL_NODE_HIGHLIGHTING,
	PATHWAY_ENABLE_ANNOTATION
}
