package org.caleydo.data.importer.tcga.startup;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.caleydo.core.data.datadomain.DataDomainConfiguration;

/**
 * Description of a data set generated by Firehose for data types such as mRNA, miR or methylation data.
 * 
 * @author Nils Gehlenborg
 * @author Marc Streit
 */
@XmlType
@XmlRootElement
public class DataTypeSet {

	private String dataPath;
	private String groupingPath; // could be empty
	private String name;
	private String colorScheme; // could be empty
	private String dataDomainType;

	public String getDataPath() {
		return dataPath;
	}

	public void setDataPath(String dataPath) {
		this.dataPath = dataPath;
	}

	public String getGroupingPath() {
		return groupingPath;
	}

	public void setGroupingPath(String groupingPath) {
		this.groupingPath = groupingPath;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getColorScheme() {
		return colorScheme;
	}

	public void setColorScheme(String colorScheme) {
		this.colorScheme = colorScheme;
	}

	/**
	 * @param dataDomainType
	 *            setter, see {@link #dataDomainType}
	 */
	public void setDataDomainType(String dataDomainType) {
		this.dataDomainType = dataDomainType;
	}

	/**
	 * @return the dataDomainType, see {@link #dataDomainType}
	 */
	public String getDataDomainType() {
		return dataDomainType;
	}

	public DataDomainConfiguration getDataDomainConfiguration() {

		DataDomainConfiguration dataConfiguration = new DataDomainConfiguration();
		dataConfiguration.setMappingFile("data/bootstrap/bootstrap.xml");

		// FIXME dynamically crate data configuration from data set information

		dataConfiguration.setRecordIDCategory("SAMPLE");
		dataConfiguration.setPrimaryRecordMappingType("SAMPLE");
		dataConfiguration.setHumanReadableRecordIDType("SAMPLE");
		dataConfiguration.setRecordDenominationPlural("samples");
		dataConfiguration.setRecordDenominationSingular("sample");

		dataConfiguration.setDimensionIDCategory("GENE");
		dataConfiguration.setPrimaryDimensionMappingType("DAVID");
		dataConfiguration.setHumanReadableDimensionIDType("GENE_SYMBOL");
		dataConfiguration.setDimensionDenominationPlural("genes");
		dataConfiguration.setDimensionDenominationSingular("gene");

		// DataDomainConfiguration mirnaConfiguration = new DataDomainConfiguration();
		// mirnaConfiguration.setRecordIDCategory("SAMPLE");
		// mirnaConfiguration.setHumanReadableRecordIDType("SAMPLE");
		// mirnaConfiguration.setRecordDenominationPlural("samples");
		// mirnaConfiguration.setRecordDenominationSingular("sample");
		//
		// mirnaConfiguration.setDimensionIDCategory("miRNA");
		// mirnaConfiguration.setHumanReadableDimensionIDType("miRNA");
		// mirnaConfiguration.setDimensionDenominationPlural("miRNAs");
		// mirnaConfiguration.setDimensionDenominationSingular("miRNA");

		// DataDomainConfiguration methylationConfiguration = new DataDomainConfiguration();
		// methylationConfiguration.setRecordIDCategory("SAMPLE");
		// methylationConfiguration.setHumanReadableRecordIDType("SAMPLE");
		// methylationConfiguration.setRecordDenominationPlural("samples");
		// methylationConfiguration.setRecordDenominationSingular("sample");
		//
		// methylationConfiguration.setDimensionIDCategory("Methylation");
		// methylationConfiguration.setHumanReadableDimensionIDType("Methylation");
		// methylationConfiguration.setDimensionDenominationPlural("methylations");
		// methylationConfiguration.setDimensionDenominationSingular("methylation");

		return dataConfiguration;
	}
}
