
package org.caleydo.data.importer.tcga.startup;

/**
 * Description of a data set generated by Firehose for data types such as mRNA, miR or methylation data.
 * 
 * @author Nils Gehlenborg
 */
public class DataTypeSet {
	
	private String dataPath;
	private String groupingPath; // could be empty
	private String name;
	private String colorScheme; // could be empty
	
	public DataTypeSet()
	{
		this.dataPath = new String();
		this.groupingPath = new String();
		this.name = new String();
		this.colorScheme = new String();
	}

	public String getDataPath() {
		return dataPath;
	}

	public void setDataPath(String dataPath) {
		this.dataPath = dataPath;
	}

	public String getGroupingPath() {
		return groupingPath;
	}

	public void setGroupingPath(String groupingPath) {
		this.groupingPath = groupingPath;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getColorScheme() {
		return colorScheme;
	}

	public void setColorScheme(String colorScheme) {
		this.colorScheme = colorScheme;
	}	
}
